### ISSUE TITLE
Question - removing geofence

### ISSUE THREAD

**Issue by talon-i-am** [safeimuslim/gmaps-geofence#1]
How does one remove the geofence altogether once it is set? When I search a city, it creates the fence, but there does not seem to be a way to delete it.

**Comment by safeimuslim** [comment]
to manipulation geofence: 
1. we must define geofence coordinate in state
2. then delete/add/edit coordinate in state
3. rerender map with new coordinate from state

**Comment by safeimuslim** [comment]
@t-hughes checkout this demo(https://safeimuslim.github.io/gmaps-geofence/) , now available remove geofencing.
